spring:
  application:
    name: configserver
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/sarpio/config-service
          uri: https://github.com/sarpio/microservice-sarpio-demo-v1
          search-paths: configserver/src/main/resources/configuration
          clone-on-start: true
          default-label: master
server:
  port: 8888