spring:
  application:
    name: configserver
  profiles:
    active: default, prod
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sarpio/config-service.git
          clone-on-start: true
          default-label: main
server:
  port: 8888