server:
  port: 8081
#  error:
#    include-message: always
#    include-binding-errors: always
#    include-exception: false
spring:
#  jackson:
#    time-zone: Europe/Warsaw
  application:
    name: users
#  profiles:
#    active: prod
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#  config:
#    import: optional:configserver:http://localhost:8888
#  h2:
#    console:
#      path: /h2
#      enabled: true
#  sql:
#    init:
#      username: sa
#  jpa:
#    hibernate:
#      ddl-auto: update
#springdoc:
#  swagger-ui:
#    path: "/swagger/"